version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db

  db:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=usuario_constancia
      - POSTGRES_PASSWORD=constancia
      - POSTGRES_DB=inadimplentes
    ports:
      - "5432:5433"

  frontend:
    build: ./Project/constancia_frontend
    volumes:
      - ./Project/constancia_frontend:/app
    ports:
      - "3030:3000"
